# Generated by Django 5.2.3 on 2025-07-09 10:35

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_tag_movie_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.image_upload_path),
        ),
    ]
